### ISSUE TITLE
email configuration needed privacy@civicactions.com

### ISSUE THREAD

**Issue by hpoole** [CivicActions/nebula#105]
we need a way to capture these emails and distribute to me and judy at least. currently the email address bounces

---

Delivery to the following recipient failed permanently:

```
 privacy@civicactions.com
```

Technical details of permanent failure:
Google tried to deliver your message, but it was rejected by the server for the recipient domain civicactions.com by aspmx.l.google.com. [2607:f8b0:400c:c06::1a].

The error that the other server returned was:
550-5.1.1 The email account that you tried to reach does not exist. Please try
550-5.1.1 double-checking the recipient's email address for typos or
550-5.1.1 unnecessary spaces. Learn more at
550 5.1.1 https://support.google.com/mail/answer/6596 gt7si42286232vdc.63 - gsmtp

**Comment by grugnog** [comment]
Added an "privacy@" alias to a group that includes Henry, Judy, Owen and Bill.

**Comment by grugnog** [comment]
Confirmed this is working
