### ISSUE TITLE
Compose Survey to get Feedback on Site

### ISSUE THREAD

**Issue by RobertLRead** [CivicActions/nebula#114]
Dear Ron and Luke, 

Here are my recommendations for a survey:
- On a scale of 1 to 10 where 1 is not like and 10 is extremely likely, how likely are you to recommend this tool to a colleague?

(This should be a selection between 1 and 10).
- What change would make you more likely to use this tool?
- If this tool were worth $100 to you, how much would it be worth with Drug Codes?
- If this tool was worth $100 to you, how much would it be worth with short Drug Descriptions?
- If this tool was worth $100 to you, how much would it be worth if it earmarked potential synergist and antagonists?

[The last 4 can be free-form text entry.  The first should should be long, and the last 3 short.)

@lukefretwell @rakanowicz

**Comment by lukefretwell** [comment]
@RobertLRead I just looked at Google Surveys and there's a cost to use (http://www.google.com/insights/consumersurveys/pricing). There is a free version but I don't think it will suffice (http://www.google.com/insights/consumersurveys/website_owners). The other option is to use Google Forms (https://docs.google.com/a/civicactions.com/forms/d/1U0ZdquvA7UipwseTutFYTJW4SF5Fo1Hb0tVpUhnOamw/edit).

I'm :+1: with the latter unless you have a better solution.

**Comment by lukefretwell** [comment]
Here what the Google form looks like:

http://civicactions.github.io/sideeffect.io/

It's not responsive, and I'm not a big fan of the scroll within the embed. @aaronpava perhaps the other option?

**Comment by lukefretwell** [comment]
Or have a fixed 'Take our user survey' band/button on the bottom of the page that links to the form.

**Comment by rakanowicz** [comment]
We also may want to consider some questions about the data presentation: 
- Are the data presented in the charts clear and understandable?
- Is there additional information you need to see in order to put the data in proper context?

Ron Akanowicz
Information Architect
ron.akanowicz@civicactions.com 
786-853-1666

CivicActions, Inc. | empowering social change
