### ISSUE TITLE
Tool tip isn't clear

### ISSUE THREAD

**Issue by rakanowicz** [CivicActions/nebula#12]
When hovering with the mouse over one of the colors in the bar chart a tool tip pops up (see attached image). 
1. The tip points to the edge of the color, between it and another color. Which is it pointing at? Can the tip be positioned in the middle of the color bar?
2. The name of the drug does not appear; replace the numeric reference and replace it with the drug name.
3. Format the number so it's easier to read 33456 -> 33,456
![tool-tip](https://cloud.githubusercontent.com/assets/12954654/8357270/0af487ea-1b28-11e5-89a2-e6011a192169.png)

**Comment by gregelin** [comment]
+1 The tool tip needs more information. Users -- who scan rather than read -- will expect the mouse over to be the big reveal of meaningful information. And maybe even a clickable event.

Greg
