### ISSUE TITLE
[HIGH] Return key does not trigger Compare button

### ISSUE THREAD

**Issue by rakanowicz** [CivicActions/nebula#16]
[HIGH] Use the keyboard Return/Enter key to trigger the Compare button.

**Comment by aravenrose** [comment]
fixed.

https://github.com/CivicActions/nebula/commit/7abed63

**Comment by rakanowicz** [comment]
It doesn't seem to be working for me.

**Comment by aravenrose** [comment]
Looks like someone commented out my code.

lines 442-448

https://github.com/CivicActions/nebula/blob/master/frontend/web/assets/nebula.js

@rakanowicz
