### ISSUE TITLE
X axis has no label (and this info should perhaps just be included as part of the "side effects" title?) 

### ISSUE THREAD

**Issue by stevecurtis** [CivicActions/nebula#22]
Something like 

Side Effects
(Absolute number of adverse events reported by users to FDA [program title] from dates X to Y) 

or some such.

**Comment by rakanowicz** [comment]
Steve, I created a revised wire earlier today that took into account feedback from Kev; he said the same thing and I do agree. See revised [wire](https://civicactions.mybalsamiq.com/projects/agile-gsa/PV-%20Drug%20List%20Vertical%20Revised%2006272015)

**Comment by ethanteague** [comment]
I can give it a label, but moving the x-axis to the top would require a big api change.

**Comment by stevecurtis** [comment]
What about just adding the language suggested above directly below the "Side Effects" title? We need some explanation of what the values on the X axis are, and it would be less cluttery to just include them up there?

**Comment by rakanowicz** [comment]
We’ve heard from a couple of people that the “Side Effects” heading at the top is confusing so that’s why I suggest just removing it. The side effects are listed on the left side of the chart and don’t describe the drug legend. And we need to be consistent with language:  side effects -> adverse effects. 

Ron Akanowicz
Information Architect
ron.akanowicz@civicactions.com 
786-853-1666

CivicActions, Inc. | empowering social change

**Comment by gregelin** [comment]
The time dimension of the reports is _really_ important. Is it 5265 adverse reports over the last month? last year? Is that big percentage of users? Small?

The lack of context is a _common_ problem with gov data. There are some tricks to address. For example:
- Compare to a common baseline (e.g., compare to reports for aspirin)
- Compare to highest and lowest
- Group stuff into categories (new drug, established drug, small user base, average user base, very large user base)

I think we could use publicly available data to categorize size of user base and ratio of reports for a dozen well known drugs (aspirin, lipitor, etc) and a few rare drugs to represent what could be done with more time.

**Comment by rakanowicz** [comment]
Greg: I posted an image in Slack a little while ago. Is that label better? See [wire](https://civicactions.mybalsamiq.com/projects/agile-gsa/PV%20-%20Drug%20List%20Vertical%20Revised%2006262015)

The details of the description need to be confirmed by DEV; but basically something like that?
