### ISSUE TITLE
[HIGH] Improve disclaimers and Attributions at bottom of the site.

### ISSUE THREAD

**Issue by RobertLRead** [CivicActions/nebula#27]
Henry pointed out that we should have two attributions:

Data provided by the U.S. Food and Drug Administration (https://open.fda.gov)
Data provided by the Department of Health and Human Services (http://meps.ahrq.gov/mepsweb/data_stats/download_data/pufs/h152a/h152adoc.shtml)

Additionally, Martha suggested that we have better disclaimers/footnotes at the bottom of the page.  Tyson suggested a disclaimer at the Top of the page.  I suggest a thin disclaimer at the top of the page, with a link to the footnote at the bottom. The footnote at the bottom should explicitly call out the limitation/disclaimers of our data sources.

**Comment by hpoole** [comment]
Rob, what is the status of this ticket?

**Comment by RobertLRead** [comment]
Not done yet. At the sprint planning meeting today it will likely be prioritized. It is a low-effort issue, I suspect it will be done by the early afternoon.

**Comment by hpoole** [comment]
ok. thanks.

On Fri, Jun 26, 2015 at 8:02 AM, Robert L. Read notifications@github.com
wrote:

> Not done yet. At the sprint planning meeting today it will likely be
> prioritized. It is a low-effort issue, I suspect it will be done by the
> early afternoon.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CivicActions/nebula/issues/27#issuecomment-115719859.

## 

Henry Poole |  +1.510.684.3180
CivicActions Inc. | Digital Platforms for a Smart Government
Washington DC - New York - San Francisco - Los Angeles

**Comment by RobertLRead** [comment]
I have added the following text.  Once pushed, you will be able to see it on the live site.  I am happy to have Ron or Luke explain how to create a visual separation----if one is needed.  @hpoole @rakanowicz @lukefretwell 

Ron, if you think it is good, please close the issue as being done, or give me further advice.
![screen shot 2015-06-26 at 1 45 18 pm](https://cloud.githubusercontent.com/assets/5296671/8384906/f57fff56-1c09-11e5-9ddd-f70391d5171a.png)

**Comment by rakanowicz** [comment]
That short paragraph bottom center- can it be moved to the first column? Those big blank spaces look odd. I'd also love to see more space in the margins among the columns.

**Comment by lukefretwell** [comment]
@RobertLRead @rakanowicz where is the text for this? I can add into the updated proto.

**Comment by lukefretwell** [comment]
NM I found.

**Comment by lukefretwell** [comment]
Addressed here: 
- https://github.com/CivicActions/sideeffect.io
- http://civicactions.github.io/sideeffect.io/

**Comment by hpoole** [comment]
thanks!

On Saturday, June 27, 2015, Robert L. Read notifications@github.com wrote:

> Closed #27.
> 
> —
> Reply to this email directly or view it on GitHub.<
> https://ci5.googleusercontent.com/proxy/-6gXLb3oggg_17WQLwmJqzbBvOG91rgn_TSirn5bdDj41QSxrhkHZS_Rm2o_GZHDEUNpum0sTGqC6Evp4upSnxI7_YmIS0cK7PtDSwCHrYoUYcImaXasdSar7PJBtFhd6FzBNtLjVNzMcUkQZkZZpC9BfCkcOg=s0-d-e1-ft#https://github.com/notifications/beacon/AMJfjczdbLLmxPC2r-dh8TIGTaKDpuuWks5oXwtDgaJpZM4FMPXi.gif

## 

I'm mobile, pardon the brevity.
