### ISSUE TITLE
Create helpful contact page

### ISSUE THREAD

**Issue by gregelin** [CivicActions/nebula#28]
Create a contact page like http://www.cdc.gov/contact/ linked to from footer that provides presents various contact points
- [x] Emergency call 911
- [x] Poison or drug hotline
- [x] FDA reporting form https://www.accessdata.fda.gov/scripts/medwatch/index.cfm?action=reporting.home
- [x] email address `privacy@civicactions.com` or `privacy@sideeffects.io` for inquiries about privacy and and security.
- [x] link to github issues page

**Comment by lukefretwell** [comment]
Addressed here:
- https://github.com/CivicActions/sideeffect.io
- http://civicactions.github.io/sideeffect.io/

@gregelin can you review? I've addressed each of the task list items in various areas on the page.
