### ISSUE TITLE
Add fork me ribbon

### ISSUE THREAD

**Issue by davenuman** [CivicActions/nebula#37]
https://github.com/blog/273-github-ribbons

**Comment by davenuman** [comment]
I think the right-hand version would work better, and maybe black or grey would suite our colour scheme better

**Comment by lukefretwell** [comment]
I will include this in the new proto.

**Comment by lukefretwell** [comment]
Addressed here: 
- https://github.com/CivicActions/sideeffect.io
- http://civicactions.github.io/sideeffect.io/
