### ISSUE TITLE
Logo adjustments

### ISSUE THREAD

**Issue by ghost** [CivicActions/nebula#39]
Please add 20px top and bottom margin to the logo.

**Comment by rakanowicz** [comment]
Is it possible to remove the ".io" from the logo? So that it just reads [pill image] sideeffect

thoughts?

**Comment by ghost** [comment]
Luke and I discussed this and decided to keep the "io" because Side Effects is trademarked. So we're trying best to not jump on anyone's toes.

**Comment by RobertLRead** [comment]
@halfstring I could add the padding, but are we sure that won't mess up the appearance on a phone?  I am loathe to tune things in Bootstrap unless we understand how they will effect the "very small" presentation.

**Comment by lukefretwell** [comment]
Addressed here: 
- https://github.com/CivicActions/sideeffect.io
- http://civicactions.github.io/sideeffect.io/
