### ISSUE TITLE
[STYLE] Use suggested color for headings

### ISSUE THREAD

**Issue by rakanowicz** [CivicActions/nebula#45]
$grass
# 00A159

For headings like: 

![image](https://cloud.githubusercontent.com/assets/12954654/8385248/fd64257a-1c14-11e5-9d8b-313e7fd33575.png)

**Comment by lukefretwell** [comment]
Addressed here: 
- https://github.com/CivicActions/sideeffect.io
- http://civicactions.github.io/sideeffect.io/
