### ISSUE TITLE
[STYLE] Can the chart bars be thinner?

### ISSUE THREAD

**Issue by rakanowicz** [CivicActions/nebula#46]
The width of the chart bars is copious. Can they be made thinner? By half? 
_I thought we were going to show 10 side effects by default?_ 
Thinner bars the user will be able to see more at once. 
![image](https://cloud.githubusercontent.com/assets/12954654/8385375/e299bac4-1c15-11e5-8d4f-91684121e567.png)

**Comment by RobertLRead** [comment]
@ethanteague @rakanowicz Yes, we can find a way to make them thinner.  I don't see any reason to limit to 10---we moved to the horizontal bars to avoid such a limit.
