### ISSUE TITLE
Want number of cases at the top of the chart.....

### ISSUE THREAD

**Issue by RobertLRead** [CivicActions/nebula#58]
Tommorow Partners mentioned this.  This is a little tricker to work out given Google Charts, but no doubt we can find some way to improve it.

**Comment by RobertLRead** [comment]
Ron has some ideas of putting in different way.

**Comment by rakanowicz** [comment]
To simply display the upper bound number at the top of the chart so that it looks like it's on the axis. 
See last [wire](https://civicactions.mybalsamiq.com/projects/agile-gsa/Drug%20List%20Vertical%20Revised%2006292015)
