### ISSUE TITLE
[HIGH] An Android phone, side effect wording is illegible.

### ISSUE THREAD

**Issue by RobertLRead** [CivicActions/nebula#63]
Possibly we can just give it more space overall.  The bar charts are needed only for comparison anyway.

**Comment by rakanowicz** [comment]
Can we place the label above the bar:
Valium
[----------------------]

I like on desktop how they are to the left; I wonder if they can "responsively" move to above the bar when viewed on tablet/mobile?

**Comment by RobertLRead** [comment]
Ron, I've cut down the bar width.  When you see it live you can decide to close this issue or we can try to make some other change.
