### ISSUE TITLE
Bar chart scrolls within the page

### ISSUE THREAD

**Issue by rakanowicz** [CivicActions/nebula#66]
The bar chart scrolls within the page and produces a second vertical scroll bar. 
The title of the chart also disappears. 
Can the entire chart be displayed on the page fixed o that when one scrolls down the Page one is also scrolling down all the side effects (so the Page is as long as the list of SEs). Keep chart title fixed in place. 

![image](https://cloud.githubusercontent.com/assets/12954654/8414165/06348a4a-1e64-11e5-9797-0a7364789a1a.png)

title gets lost:
![img_0031](https://cloud.githubusercontent.com/assets/12954654/8414173/190126e2-1e64-11e5-90ec-53d94bddc958.PNG)

**Comment by RobertLRead** [comment]
@rakanowicz I suspect this cannot be done.  I tried it over the weekend, and basically Google Charts has some weaknesses that make this bad.  I would like to suggest this be moved to "LOW".

**Comment by rakanowicz** [comment]
Can the title "Reported Side Effects" be fixed? taken off chart and added to page?

**Comment by ethanteague** [comment]
@rakanowicz | @RobertLRead: I can fix this so that there is no scroll, in fact, that is the default behavior. I put in the scroll, and a container div.
