### ISSUE TITLE
Color scheme should change to match style guide

### ISSUE THREAD

**Issue by RobertLRead** [CivicActions/nebula#9]
Chuck produced a short style guide, we need to use that.

**Comment by ghost** [comment]
Updated style guide attached.

![sideeffect_styleguide](https://cloud.githubusercontent.com/assets/13037646/8369454/d299f4a6-1b6e-11e5-8135-918760f9dbad.png)

If you want to copy and paste the hex values, download the PDF: https://www.dropbox.com/s/lzpg4k76h882qfl/SideEffect_StyleGuide.pdf?dl=0

**Comment by RobertLRead** [comment]
Ethan did most of this then I adjusted the order of the colors. I removed "silver" from the graphs because it is too close to white for that purpose.
